"""Update C3DFile model to inherit from BaseModel

Revision ID: 570323dbc186
Revises: fbbbe08e8c94
Create Date: 2025-03-23 15:27:43.901064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '570323dbc186'
down_revision: Union[str, None] = 'fbbbe08e8c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c3dfile', sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c3dfile', 'filepath')
    # ### end Alembic commands ###
