"""Add filepath to C3DFile model

Revision ID: fbbbe08e8c94
Revises: 8c195bd3d655
Create Date: 2025-03-23 15:23:33.506987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fbbbe08e8c94'
down_revision: Union[str, None] = '8c195bd3d655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('c3dfile') as batch_op:
        batch_op.drop_column('subject_name')
        batch_op.add_column(sa.Column('subject_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('c3dfile') as batch_op:
        batch_op.drop_column('subject_name')
        batch_op.add_column(sa.Column('subject_name', sa.String(), nullable=False))
    op.drop_column('c3dfile', 'filepath')
    # ### end Alembic commands ###
